### ISSUE TITLE
iOS scan not producing any report

### ISSUE THREAD

**Issue by cynthiabaran** [insidersec/insider#16]
Hey everyone,

Since v2.0.0 I haven't been able to get an report from an iOS project scan. It worked normally before that. Maybe something changed in how an analysis should be performed? Anyone else having this issue?

**Describe the bug**
When trying to perform an analysis of an iOS project, Insider exits without writing any report file.

**To Reproduce**
Run Insider v2.0.0 on macOS on an iOS project
```
./insider-macos-amd64 -tech ios -target ~/ios-project
```
**Expected behavior**
Insider would have generated the reports. It does work for analysis of other technologies.

**Desktop**
 - OS: macOS Catalina
 - Version: 2.0.0
 - Commit: aca156b on master

**Comment by hermescanutodesouza** [comment]
Hi, Could  you send the log or a output print?

**Comment by cynthiabaran** [comment]
```
[INSIDER]: 2020/06/26 15:03:46 Starting analysis for iOS app #
[INSIDER]: 2020/06/26 15:03:46 Starting iOS Source code analysis
[INSIDER]: 2020/06/26 15:03:46 Extracting libraries
[INSIDER]: 2020/06/26 15:03:47 Starting analysis on PList and XCodeProj files
[INSIDER]: 2020/06/26 15:03:48 lstat /ios-project/example/Proj: no such file or directory
[INSIDER]: 2020/06/26 15:03:48 Finished analysis for iOS app #
[INSIDER]: 2020/06/26 15:03:48 lstat /ios-project/example/Proj: no such file or directory
```

This `Proj` file does not really exists, but `Proj.xcodeproj` does.

**Comment by cynthiabaran** [comment]
Also, I can't perform an analysis on a Android project as well. Here are the logs

```
[INSIDER]: 2020/06/26 15:10:59 Starting analysis for Android target /Users/cynthia.baran/android-project
[INSIDER]: 2020/06/26 15:10:59 Starting Android source code analysis
[INSIDER]: 2020/06/26 15:10:59 Starting Android Manifest analysis
[INSIDER]: 2020/06/26 15:10:59 Loading manifest permission
[INSIDER]: 2020/06/26 15:10:59 198
[INSIDER]: 2020/06/26 15:11:00 Error: strconv.ParseBool: parsing "@bool/enable_system_alarm_service_default": invalid syntax
[INSIDER]: 2020/06/26 15:11:00 Finished analysis for Android app #/Users/cynthia.baran/android-project
[INSIDER]: 2020/06/26 15:11:00 strconv.ParseBool: parsing "@bool/enable_system_alarm_service_default": invalid syntax
```

I tried recompiling and running the old version again and everything works as expected...

**Comment by dvelardez** [comment]
The same happens to me, I send my log:

% ./insider --tech ios --target <projectfolder>

[INSIDER]: 2020/06/26 15:27:02 Starting analysis for iOS app #
[INSIDER]: 2020/06/26 15:27:02 Starting iOS Source code analysis
[INSIDER]: 2020/06/26 15:27:02 Extracting libraries
[INSIDER]: 2020/06/26 15:27:02 Starting analysis on PList and XCodeProj files
[INSIDER]: 2020/06/26 15:27:02 Finished PList/XCodeProj analysis
[INSIDER]: 2020/06/26 15:27:02 Removing: [] from file list from ios tech
[INSIDER]: 2020/06/26 15:27:02 Removing: [] from file list from ios tech
[INSIDER]: 2020/06/26 15:27:02 Found 198 files to analyze.
[INSIDER]: 2020/06/26 15:27:02 loading core rules
[INSIDER]: 2020/06/26 15:27:02 Rules 8
[INSIDER]: 2020/06/26 15:27:02 loading IOS rules
[INSIDER]: 2020/06/26 15:27:02 Rules 25
[INSIDER]: 2020/06/26 15:27:02 Rules 25
[INSIDER]: 2020/06/26 15:27:02 Starting extracting hardcoded information
[INSIDER]: 2020/06/26 15:27:07 read <projectfolder>/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers: is a directory
[INSIDER]: 2020/06/26 15:27:07 Finished analysis for iOS app #
[INSIDER]: 2020/06/26 15:27:07 read <projectfolder>/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers: is a directory

**Comment by GouveaHeitor** [comment]
@cynthiabaran and @dvelardez, 

We believe that PR #17 solved the problems you sent us! Please test the new code and let us know if everything is right :smile:

Thx!

**Comment by dvelardez** [comment]
Unfortunately it has not worked, exactly the same output.

**Comment by cynthiabaran** [comment]
For me it did fix it.

Although, I need to say I've noticed that all analysis are taking quite a bit more time to complete since release v2... Is there any reason for that?

**Comment by hermescanutodesouza** [comment]
> Unfortunately it has not worked, exactly the same output.
Did you put insider outside of the source folder ?

**Comment by hermescanutodesouza** [comment]
@dvelardez Did you put insider outside of the source folder ?

**Comment by dvelardez** [comment]
> @dvelardez Did you put insider outside of the source folder ?

Yes!

**Comment by hermescanutodesouza** [comment]
@dvelardez , could you send the log or a print ?

**Comment by dvelardez** [comment]
> @dvelardez , could you send the log or a print ?

jenkins@myserver ~ % ./insider-macos-amd64 --tech ios  --target /Users/jenkins/workspace/servicios_centrales/servicios_centrales.lala-mobile-ios.ci -v 

-===========================================================================================================-
  ▄█  ███▄▄▄▄      ▄████████  ▄█  ████████▄     ▄████████    ▄████████    ▄████████    ▄████████  ▄████████
 ███  ███▀▀▀██▄   ███    ███ ███  ███   ▀███   ███    ███   ███    ███   ███    ███   ███    ███ ███    ███
 ███▌ ███   ███   ███    █▀  ███▌ ███    ███   ███    █▀    ███    ███   ███    █▀    ███    █▀  ███    █▀
 ███▌ ███   ███   ███        ███▌ ███    ███  ▄███▄▄▄      ▄███▄▄▄▄██▀   ███         ▄███▄▄▄     ███
 ███▌ ███   ███ ▀███████████ ███▌ ███    ███ ▀▀███▀▀▀     ▀▀███▀▀▀▀▀   ▀███████████ ▀▀███▀▀▀     ███
 ███  ███   ███          ███ ███  ███    ███   ███    █▄  ▀███████████          ███   ███    █▄  ███    █▄
 ███  ███   ███    ▄█    ███ ███  ███   ▄███   ███    ███   ███    ███    ▄█    ███   ███    ███ ███    ███
 █▀    ▀█   █▀   ▄████████▀  █▀   ████████▀    ██████████   ███    ███  ▄████████▀    ██████████ ████████▀
                                                            ███    ███
-===========================================================================================================-

[INSIDER]: 2020/07/01 11:17:26 Starting analysis for iOS app #
[INSIDER]: 2020/07/01 11:17:26 Starting iOS Source code analysis
[INSIDER]: 2020/07/01 11:17:26 Extracting libraries
[INSIDER]: 2020/07/01 11:17:26 Removing: [] from file list from ios tech
[INSIDER]: 2020/07/01 11:17:26 Removing: [] from file list from ios tech
[INSIDER]: 2020/07/01 11:17:26 Found 198 files to analyze.
[INSIDER]: 2020/07/01 11:17:26 loading core rules
[INSIDER]: 2020/07/01 11:17:26 Rules 8
[INSIDER]: 2020/07/01 11:17:26 loading IOS rules
[INSIDER]: 2020/07/01 11:17:26 Rules 25
[INSIDER]: 2020/07/01 11:17:26 Rules 25
[INSIDER]: 2020/07/01 11:17:26 Starting extracting hardcoded information
[INSIDER]: 2020/07/01 11:17:31 read /Users/jenkins/workspace/servicios_centrales/servicios_centrales.lala-mobile-ios.ci/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers: is a directory
[INSIDER]: 2020/07/01 11:17:31 Finished analysis for iOS app #
[INSIDER]: 2020/07/01 11:17:31 read /Users/jenkins/workspace/servicios_centrales/servicios_centrales.lala-mobile-ios.ci/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Headers: is a directory

**Comment by hermescanutodesouza** [comment]
Hi !
Could you delete the PODS folder
The PODS folder contains dependencies, which are not analyzed by the insider.

**Comment by dvelardez** [comment]
> Hi !
> Could you delete the PODS folder?
> The PODS folder contains dependencies, which are not analyzed by the insider.

It worked! Is it possible to incorporate a parameter that allows exclusions?
Thank you very much!

**Comment by umarhyatt00** [comment]
I am scanning iOS code but not getting any result because scanning doesn't start. Below is the output:

sudo ./insider --tech ios --target /home/test/Downloads/project-folder
[insider] 2021/07/12 18:44:09 Starting analysis
[insider] 2021/07/12 18:44:09 Analysing IOS libraries
[insider] 2021/07/12 18:44:10 Analysing IOS plist files
[insider] 2021/07/12 18:44:11 Not found plist files at /home/test/Downloads/project-folder
[insider] 2021/07/12 18:44:11 Starting source code analysis
[insider] 2021/07/12 18:44:11 Analysing files on directory /home/test/Downloads/project-folder
