### ISSUE TITLE
NewInputFile throws an unhandled exception, with both javascript and C#

### ISSUE THREAD

**Issue by billionai** [insidersec/insider#44]
When analising a project with many subfolders containing code, after insidersec starts main code analysis newInputFile seems to have trouble with an unhandled exception, crashing the program and leaving basically no information to help with debugging

**To Reproduce**
Not sure how to help with reproductibility, since I don't know which file causes the problem, or if subfolders are the problem, and I can not share any part of the project I'm working on

**Expected behavior**
I expected the program to keep running, and preferably to warn me that one or more files caused a problem and couldn't be analised

**Screenshots**
log from when analizing the C# part:
![image](https://user-images.githubusercontent.com/31167038/100132713-910ba980-2e64-11eb-8747-5b9f2d77d9f0.png)

Log from when analizing the javascript part:
![image](https://user-images.githubusercontent.com/31167038/100133134-23ac4880-2e65-11eb-9eb2-ad07d849d6fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Release: 2.0.5

**Comment by msAlcantara** [comment]
Thanks for the issue, and sorry for delay. This issue seems to already fix in [this commit](https://github.com/insidersec/insider/commit/79d5cc931a934bee4bcc158567f8c773658bbb45). We are preparing to make a new release with these fixes.

**Comment by msAlcantara** [comment]
Closing the issue because version [2.0.6](https://github.com/insidersec/insider/releases/tag/2.0.6) is released
