### ISSUE TITLE
Where is the outputs folder?

### ISSUE THREAD

**Issue by aaronesau-summit** [insidersec/insider#7]
Where is the outputs folder? Someone should specify it in the README.md and help menu too if possible.

**Comment by aaronesau-summit** [comment]
Hm it won't let me get rid of the `bug` label, sorry

**Comment by aaronesau-summit** [comment]
Ah, found it. It is literally `results`. Thanks!

https://github.com/insidersec/insider/blob/1d875f49c528d59fe03ae98d28b00006b60f45c0/supervisors/hypervisor.go#L15

**Comment by omatron** [comment]
Hello @aaronesau-summit  thanks for the feedback, do you think this pull request solves the issue?
https://github.com/insidersec/insider/pull/8

**Comment by aaronesau-summit** [comment]
Yes, the info you added is helpful. I'll close this in advance. Thanks!
